name: Generate Snake Contribution Graph

on:
  schedule: # Runs once a day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake (light + dark)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-light.svg?palette=github-light
            dist/snake-dark.svg?palette=github-dark

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
